name: nf-test-repro
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10.*
  - ruff>=0.2.1
  - mypy>=1.8
  # Nextflow
  - nextflow>=23.10,<24
  - pytest>=8.0.0
  - pytest-workflow=2.1.0
  - nf-test=0.9.0
  # Other
  - shellcheck>=0.9
  - cutadapt=4.9.*
